import turtle
# turtle.setposition(500, 500)
turtle.color("red")
turtle.speed(1)
# turtle.right(90)
turtle.left(90)
turtle.forward(150)
turtle.right(180)
turtle.backward(50)
turtle.circle(50, None, None)
turtle.down()