user22:
    name: 老王
    age: 33
    cat:
      name: tomcat

mycar:
  brand: ms
  price: 1000000000

#配置
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdemo?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    指定启动的banner图像
  banner:
    image:
      location: banner.txt
  #指定资源默认目录
  web:
    resources:
      static-locations:
        [classpath:/static/]
  mvc:
    #    static-path-pattern: /res/** #  访问资源的前缀
    contentnegotiation:
      favor-parameter: true      #开启请求参数内容协商模式