spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdemo?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall
      aop-patterns: com.raisei.bootdemo01.*
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        stat:
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false
  redis:
    port: 6379
    host: localhost
    password: noesis360724
    client-type: jedis
#    可视化监控
  boot:
    admin:
      client:
        url: http://127.0.0.1:8888 #指向监控服务器
        instance:
          prefer-ip: true #使用IP注册
  application:
    name: boot-demo-01

#    url: redis://user:password@127.0.0.1:6379

#  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 80
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# jvm端点管理
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true #开启所有监控端点
    web:
      exposure:
        include: "*" #以web形式暴露所有监控端点
info:
  version: 1.0.0
  SpringBoot: "2.4.3"

