# Project: DataStructDemo
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = StackDemo.o BiTreeDemo.o
LINKOBJ  = StackDemo.o BiTreeDemo.o
LIBS     = -L"D:/Program Files Code/Dev-Cpp/MinGW64/lib" -L"D:/Program Files Code/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Program Files Code/Dev-Cpp/MinGW64/include" -I"D:/Program Files Code/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files Code/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Program Files Code/Dev-Cpp/MinGW64/include" -I"D:/Program Files Code/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Program Files Code/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Program Files Code/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DataStructDemo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

StackDemo.o: StackDemo.c
	$(CC) -c StackDemo.c -o StackDemo.o $(CFLAGS)

BiTreeDemo.o: BiTreeDemo.c
	$(CC) -c BiTreeDemo.c -o BiTreeDemo.o $(CFLAGS)
